### ISSUE TITLE
Playlists + Ads not working properly

### ISSUE THREAD

**Issue by gabrieli** [brightcove/videojs-playlist#20]
I'm using the latest version of videojs-contrib-ads alongside with videojs-playlists. 
The playlist is listening for the 'ended' event for triggering the next video player.one('ended', ontimeout) and I thought that by using contrib-ads all would work fine, as the 'ended' events should have been suppressed during ads, so 'ended' would have been fired only on content end. 

Instead, I see the ontimeout function being triggered on ad end (preroll end) and when the content ends, the callback is not fired again.

**Comment by simshanith** [comment]
@gabrieli - you should use the ads plugin prefixed `contentended` event to listen to content-specific ended events.

**Comment by gabrieli** [comment]
Thanks for the reply @simshanith! It's not me listening for 'ended', it's the playlist. I see the code has changed a bit since I've reported the issue, but the problem seems to be still there
https://github.com/brightcove/videojs-playlist/blob/master/src/auto-advance.js#L54

**Comment by simshanith** [comment]
Hmm... My team also has worked with both plugins.

I believe if you initialize the ads plugin before the initializing the playlist plugin, the `ended` event will be properly suppressed and prefixed with `content` by the ads plugin before propagating to the playlist plugin. However, this may mean you need to implement your own auto-advance functionality.

Hope that helps.

**Comment by gabrieli** [comment]
@simshanith Thanks again for the feedback! 
We're a 3rd party vendor doing a plug-and-play solution on top of the contrib-ads, and managing the internals of the playlist, from inside the ad plugin would be unnatural and prone to maintenance issues (we've tried and talking from experience). Also, as our plugin does not come bundled with the playlist, it's a bit harder to enforce a certain loading order. But if this would work, we might need to consider it.

**Comment by gkatsev** [comment]
Sorry for the late reply. One thing to be aware is that you want to make sure that the playlist plugin is loaded *after* contrib-ads/ads plugin is loaded because otherwise contrib-ads doesn't have a chance to redispatch the `ended` event has `contentended`.
I've implemented playlist support using videojs-playlist and contrib-ads and generally it requires fixes in the ad integration. However, it's also possible that there are bugs on the contrib-ads side.
Hope that helps, and let us know if you need more help. Closing because I don't think it's a videojs-playlist issue. Discussion can continue.
