### ISSUE TITLE
Adding source items dynamically

### ISSUE THREAD

**Issue by azcoppen** [brightcove/videojs-playlist#52]
In the player i'm building, i have to preload the first item, then send the remainder of the playlist to a background loop that resolves URLs. Once the list has been resolved, it needs to be appended to the current playlist. The transition needs to be invisible.

Is it possible to append to the existing playlist, either directly using push() on the sources array, or by some kind of append() operation?

**Comment by gkatsev** [comment]
Unfortunately, there's nothing like that right now. You can probably do a workaround right now since the `playlist` function can now [accept an index to start it](https://github.com/brightcove/videojs-playlist/blob/master/docs/api.md#playerplaylistarray-newlist-number-newindex---array).

We're probably not going to make such a feature ourselves but I don't think anyone ( @misteroneill, @mister-ben, @incompl, @dmlap ) would be opposed.

**Comment by azcoppen** [comment]
@gkatsev Thanks for clarifying. Basic logic there would be to load the playlist with 1 (first) item (index 0), then load it again after it's finished playing with the full list again, and start at index 1 (item 2). Will post some sample code to help anyone who wants to do the same once i get it working. Thanks again!

**Comment by mister-ben** [comment]
Definitely not opposed. Appending items could be pretty useful.
