### ISSUE TITLE
Playlist Autoplay

### ISSUE THREAD

**Issue by tsetzler** [brightcove/videojs-playlist#56]
I made a list of 4 videos, as soon as you get to the site the first video is to play and go to the next.

The first video keeps looping, never goes to the second video or any others.

**Comment by lucasprates** [comment]
I'm having an issue similar to this.
Mine only plays one of X vids in the playlist. It does not trigger the others, while they are, indeed, still stored in the list.

I think it is doing this because of something related to the fact that this library uses a version of videojs different of the one I am using (I think they use one version below) of the one videojs has on their site for download or on npm.

**Comment by RemcoTukker** [comment]
I think it's a typo in the code:
`player.one('ended', player.playlist.autoadvance_.trigger);`
should be
`player.on('ended', player.playlist.autoadvance_.trigger);`

Also note that fragments don't trigger the ended event and if you're reading from file:// on windows you should use a capital for the drive letter (because the playlist indexof function is slightly bugged and doesnt consider C: the same as c: . May also give trouble for the rest of the filename?)
